# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via \{\{ site.title \}\}, \{\{ site.github_repo \}\}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via \{\{ site.myvariable \}\}.
title: "Stat 158:  Experimental Design"
tagline: Course Overview
description: This course will review the statistical foundations of randomized experiments and study principles for addressing common setbacks in experimental design and analysis in practice. We will cover the notion of potential outcomes for causal inference and the Fisherian principles for experimentation (randomization, blocking, and replications). We will also cover experiments with complex structures (clustering in units, factorial design, hierarchy in treatments, sequential assignment, etc). We will also address practical complications in experiments, including noncompliance, missing data, and measurement error. This course uses R as its primary computing language; details are determined by the instructor.

author: SCF
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://stat158.berkeley.edu'
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]
logo: 'resources/stat_bear.png'

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.7.0
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false